name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET (v2.1)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 2.1.x

      - name: Install .NET (v5.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Reset NuGet locals
        run: dotnet nuget locals all --clear

      - name: Build & test (.NET v2.1)
        # Doesn't support test loggers
        run: dotnet test --configuration Release --framework netcoreapp2.1

      - name: Build & test (.NET v5.0)
        run: dotnet test --configuration Release --logger GitHubActions --framework net5.0

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
